2025-09-11 13:18:35,448 - framework.data_ingestion - DEBUG - [Data Ingestion] : Dataset Exp-1_iot loaded.
2025-09-11 13:18:35,448 - root - DEBUG - [Data Ingestion] : Datasets Ingested: 1
2025-09-11 13:18:35,448 - root - DEBUG - [Data Prepocessing] : Training data loaded with devices: ['smartplug-kp105', 'ilife_t10s', 'chromecast_v3', 'nest_smokealarm', 'calex_slimme_led_vloerlamp', 'echo_dot', 'smartplug-hs110', 'calex_motion_sensor', 'bosch_dishwasher', 'ring_doorbell', 'welltobe_pet_feeder', 'samsung_fridge', 'pni_safe_house_pg600lr', 'salcar_radiatorthermostaat_trv801w', 'philips_tv', 'princess_smart_aerofryer', 'google_nest_cam', 'philips_luchtreiniger_600-serie', 'google_home_mini', 'philips_hue', 'watersensor', 'amazon_echo'], Testing data loaded with devices: ['smartplug-kp105', 'ilife_t10s', 'chromecast_v3', 'nest_smokealarm', 'calex_slimme_led_vloerlamp', 'echo_dot', 'smartplug-hs110', 'calex_motion_sensor', 'bosch_dishwasher', 'ring_doorbell', 'welltobe_pet_feeder', 'samsung_fridge', 'pni_safe_house_pg600lr', 'salcar_radiatorthermostaat_trv801w', 'philips_tv', 'princess_smart_aerofryer', 'google_nest_cam', 'philips_luchtreiniger_600-serie', 'google_home_mini', 'philips_hue', 'watersensor', 'amazon_echo']
2025-09-11 13:18:36,698 - root - DEBUG - Generated Model Training Class:GenIoTIDTraining
2025-09-11 13:18:36,698 - root - DEBUG - <class 'GenIoTIDTraining.GenIoTIDTraining'>
2025-09-11 13:18:36,699 - root - DEBUG - Generated Model Test Class: GenIoTIDTesting
2025-09-11 13:18:36,700 - root - DEBUG - <class 'GenIoTIDTesting.GenIoTIDTesting'>
2025-09-11 13:18:36,700 - root - DEBUG - Training Dataset: Exp-1_iot
2025-09-11 13:18:36,700 - root - DEBUG - Testing Dataset: Exp-1_iot
2025-09-11 13:18:36,700 - root - DEBUG - Cross Validation: True
2025-09-11 13:18:36,700 - framework.model_training - ERROR - [GenIoTID training] : No module named 'process_data'
Traceback (most recent call last):
  File "/home/chakshu/Documents/codebase/evaliot/framework/eval_modules/geniotid_training.py", line 29, in __init__
    from process_data import process_pcap, get_flows
ModuleNotFoundError: No module named 'process_data'
2025-09-11 13:18:36,700 - framework.model_training - ERROR - [GenIoTID training] : ERROR importing the GenIoTID code from the repo or loading the training dataset
2025-09-11 13:18:36,700 - root - DEBUG - Model Train Class Initialized! Running the command to train the model...
2025-09-11 13:18:36,701 - framework.model_training - ERROR - [GenIoTID training] : No module named 'train_test_model'
Traceback (most recent call last):
  File "/home/chakshu/Documents/codebase/evaliot/framework/eval_modules/geniotid_training.py", line 91, in run
    from train_test_model import train_model
ModuleNotFoundError: No module named 'train_test_model'
2025-09-11 13:18:36,701 - root - DEBUG - [Model Training]: Result: True
2025-09-11 13:18:36,701 - root - ERROR - [Model Training] : ERROR! Unable to run the command to train the model!
